export const GET_INVENTORIES_REQUEST = "GET_INVENTORIES_REQUEST";
export const GET_INVENTORIES_SUCCESS = "GET_INVENTORIES_SUCCESS";
export const GET_INVENTORIES_FAILURE = "GET_INVENTORIES_FAILURE";

export const GET_INVENTORY_DETAILS_REQUEST = "GET_INVENTORY_DETAILS_REQUEST";
export const GET_INVENTORY_DETAILS_SUCCESS = "GET_INVENTORY_DETAILS_SUCCESS";
export const GET_INVENTORY_DETAILS_FAILURE = "GET_INVENTORY_DETAILS_FAILURE";
export const GET_INVENTORY_DETAILS_RESET = "GET_INVENTORY_DETAILS_RESET";
